language: node_js
before_install:
  - sh ./travis_scripts/$TRAVIS_OS_NAME.sh
node_js:
  - "7"
script:
  - npm install
  - npm test
matrix:
  include:
    - os: linux
      dist: trusty
      env: LD_LIBRARY_PATH=/tmp/ice-node-lib LIBRARY_PATH=/tmp/ice-node-lib
